# Generated by Django 2.1.7 on 2019-03-22 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeinventorytracking', '0002_auto_20190322_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homeinventorytracking.Structure'),
        ),
    ]
