# Generated by Django 2.1.7 on 2019-03-22 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeinventorytracking', '0003_auto_20190322_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeinventorytracking.Structure'),
        ),
    ]
