# Generated by Django 2.1.7 on 2019-03-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeinventorytracking', '0005_structure_object_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='object_value',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]
